"""empty message

Revision ID: 42640e29cb62
Revises: 30c07c29b672
Create Date: 2020-12-23 14:20:15.602620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42640e29cb62'
down_revision = '30c07c29b672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_string', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('new_string')

    # ### end Alembic commands ###
